[package]
name = "rlox"
version = "0.1.0"
authors = ["jamesfarrell"]
edition = "2018"

[dependencies]
phf = { version = "0.8", features = ["macros"] }
num_enum = { version = "0.4.2" }
strum = "0.17.1"
strum_macros = "0.17.1"
